### ISSUE TITLE
set up wyze

### ISSUE THREAD

**Issue by pi642s** [whiskerz007/proxmox_hassio_lxc#27]
I followed the direction to create a new container and run set_autodev_hook.sh . 

however can't see  /dev/hidraw0.

i saw in the closed issues someone had a similar problem before, i tried his script but didn't work either.  

Running ls -l /dev/hidraw0

From the container:
ls: cannot access '/dev/hidraw0': No such file or directory

From the Host:
crw------- 1 root root 240, 0 May 22 21:03 /dev/hidraw0

**Comment by whiskerz007** [comment]
I've pushed a change to `set_autodev_hook.sh` that should encompass your hardware. Please follow the instructions [here](https://github.com/whiskerz007/proxmox_hassio_lxc#update-device-hooks) and report back if the problem is, or is not, resolved.

**Comment by pi642s** [comment]
wow it did work!  thank you so much!  



ls -l /dev/hidraw0
crw------- 1 root root 242, 0 May 26 17:40 /dev/hidraw0

**Comment by pi642s** [comment]
this is just so awesome.  i re-installed proxmox-hassio-lcx, then installed add on  hassio-google-drive-backup, restored the back up file and everything worked!  everything took less than 10 minutes to set up.  thanks again whiskerz007!

**Comment by pi642s** [comment]
Hi whiskerz007

if you can please help again.

i moved everything from an old surface to an intel nuc 10 and again -l /dev/hidraw0  would show no such file or directory.  i kept running the set_autodev_hook.sh and kept reinstalling but still doesn't work.

**Comment by pi642s** [comment]
nvm, please forgive me!  i upgraded promox and now everything worked.
